### PR TITLE
add new logo to repo

### PR DESCRIPTION
**Pull request by mustafasoylu**
I added the new logo to the repo. You can see I changed the favicon logo on the docs page. I also added the logo with text to the beginning of readme. 
Screenshot from 2023-12-07 12-42-20

### CODE REVIEW

**Comment by mustafasoylu** [comment]
@apirogov if you also have any feedback about the placement and usage of the new logo, please let me know

**Comment by apirogov** [comment]
Well, there are the options of putting the image
* above the text headline, or
* below

and the variation in alignment.

I am not sure about either combination being "better", just want to point out I did it for [dirschema](https://github.com/Materials-Data-Science-and-Informatics/dirschema) in exactly the "opposite" way :rofl: 

So TL;DR: LGTM, but maybe we should agree on a consistent way of doing it for our repos

**Comment by hofmannv** [comment]
FYI: I am pro "having it halfway consistent", but no strong feelings about how exactly.

**Comment by mustafasoylu** [comment]
I feel like the logo is getting in the way of context if it is after the title; this is why I put it before the title. Of course, both ways work perfectly in my opinion 😄

**Comment by mustafasoylu** [comment]
@hofmannv I gave the direct links of github to show logos. If we change the logos at a later time, the naming should be consistent or we will have broken links in our readme and documentations.

**Comment by hofmannv** [comment]
yes - that is why they are in an open git repo (i.e. to be usable from there). We could actually think about PURLs... ;-)

**Pull request merged**
