### PR TITLE
codemeta creation

### PR DESCRIPTION
**Pull request by mustafasoylu**
create a basic codemeta.json file and get rid of codemetapy dependency, enable usage in windows

### CODE REVIEW

**Review by apirogov — APPROVED** [review]
One minor thing - shouldn't the `create.py` be better named `writer.py` (just for consistency with the oder supported file types)?

Other than that - nice, LGTM!

**Comment by mustafasoylu** [comment]
@apirogov I forgot to rename after deleting old files, updated it now

**Comment by mustafasoylu** [comment]
I tried it in my Windows PC too, it worked without problems, as it did in testing pipeline.

**Comment by mustafasoylu** [comment]
resolves #63  #48  #49

**Pull request merged**
