### PR TITLE
Migration to Pydantic 2 + codemetapy update

### PR DESCRIPTION
**Pull request by apirogov**
* Updated dependencies and migrated models to Pydantic 2 and made sure tests all work
* updated codemetapy, disabled workaround with graph equivalence testing, and adapted tests

This is based on #45 so 

* first #45 should be completed and merged
* then this PR should merge from main
* then this can be reviewed and merged

### CODE REVIEW

**Review by mustafasoylu — CHANGES_REQUESTED** [review]
I tried it with Windows 11 and codemeta.json creation created a permission denied error.

**Comment by mustafasoylu** [comment]
Windows permission denied error debug log:

```bash
VERBOSE  Updating codemeta.json file.                                                                                                                                                                                                                                                                                                                 sync.py:97
DEBUG    Running codemetapy with sources [WindowsPath('pyproject.toml'), WindowsPath('C:/Users/MUSTAF~1/AppData/Local/Temp/cff_cm_rmhaysnj.json')]                                                                                                                                                                                                    exec.py:23
ERROR    Error: [Errno 13] Permission denied: 'C:\\Users\\MUSTAF~1\\AppData\\Local\\Temp\\cff_cm_rmhaysnj.json'                                                                                                                                                                                                                                       util.py:24
DEBUG    Traceback (most recent call last):                                                                                                                                                                                                                                                                                                           util.py:25
           File "C:\Users\Mustafa Soylu\Documents\Projects\fzj\somesy\src\somesy\cli\util.py", line 21, in wrap_exceptions                                                                                                                                                                                                                            
             return wrapped(*args, **kwargs)                                                                                                                                                                                                                                                                                                          
           File "C:\Users\Mustafa Soylu\Documents\Projects\fzj\somesy\src\somesy\cli\sync.py", line 117, in sync                                                                                                                                                                                                                                      
             run_sync(somesy_input)                                                                                                                                                                                                                                                                                                                   
           File "C:\Users\Mustafa Soylu\Documents\Projects\fzj\somesy\src\somesy\cli\sync.py", line 140, in run_sync                                                                                                                                                                                                                                  
             sync_command(somesy_input)                                                                                                                                                                                                                                                                                                               
           File "C:\Users\Mustafa Soylu\Documents\Projects\fzj\somesy\src\somesy\commands\sync.py", line 39, in sync                                                                                                                                                                                                                                  
             _sync_codemeta(conf)                                                                                                                                                                                                                                                                                                                     
           File "C:\Users\Mustafa Soylu\Documents\Projects\fzj\somesy\src\somesy\commands\sync.py", line 98, in _sync_codemeta                                                                                                                                                                                                                        
             if update_codemeta(conf):                                                                                                                                                                                                                                                                                                                
           File "C:\Users\Mustafa Soylu\Documents\Projects\fzj\somesy\src\somesy\codemeta\__init__.py", line 51, in update_codemeta                                                                                                                                                                                                                   
             cm_harvest = gen_codemeta(cm_sources)                                                                                                                                                                                                                                                                                                    
           File "C:\Users\Mustafa Soylu\Documents\Projects\fzj\somesy\src\somesy\codemeta\exec.py", line 25, in gen_codemeta                                                                                                                                                                                                                          
             g, res, args, _ = build(                                                                                                                                                                                                                                                                                                                 
           File "C:\Users\Mustafa Soylu\Documents\Projects\fzj\somesy\.venv\lib\site-packages\codemeta\codemeta.py", line 678, in build                                                                                                                                                                                                               
             with getstream(source) as f:                                                                                                                                                                                                                                                                                                             
           File "C:\Users\Mustafa Soylu\Documents\Projects\fzj\somesy\.venv\lib\site-packages\codemeta\common.py", line 890, in getstream                                                                                                                                                                                                             
             return open(source,'r',encoding='utf-8')                                                                                                                                                                                                                                                                                                 
         PermissionError: [Errno 13] Permission denied: 'C:\\Users\\MUSTAF~1\\AppData\\Local\\Temp\\cff_cm_rmhaysnj.json         ```

**Comment by mustafasoylu** [comment]
Also, I saw this error in reading package,json input. I will check it too

```bash
DEBUG    Path package.json                                                                                                                                                                                                                                                                                                                            core.py:66
VERBOSE  Using 'package.json' as somesy input file.                                                                                                                                                                                                                                                                                                   core.py:44
DEBUG    Path package.json                                                                                                                                                                                                                                                                                                                            core.py:66
ERROR    Error: 1 validation error for SomesyInput                                                                                                                                                                                                                                                                                                    util.py:24
         project.repository                                                                                                                                                                                                                                                                                                                           
           URL input should be a string or URL                                                                                                                                                                                                                                                                                                        
             For further information visit https://errors.pydantic.dev/2.4/v/url_type                                                                                                                                                                                                                                                                 
DEBUG    Traceback (most recent call last):                                                                                                                                                                                                                                                                                                           util.py:25
           File "C:\Users\Mustafa Soylu\Documents\Projects\fzj\somesy\src\somesy\cli\util.py", line 21, in wrap_exceptions                                                                                                                                                                                                                            
             return wrapped(*args, **kwargs)                                                                                                                                                                                                                                                                                                          
           File "C:\Users\Mustafa Soylu\Documents\Projects\fzj\somesy\src\somesy\cli\sync.py", line 106, in sync                                                                                                                                                                                                                                      
             somesy_input = resolved_somesy_input(                                                                                                                                                                                                                                                                                                    
           File "C:\Users\Mustafa Soylu\Documents\Projects\fzj\somesy\src\somesy\cli\util.py", line 48, in resolved_somesy_input                                                                                                                                                                                                                      
             somesy_input: SomesyInput = somesy_conf.get_input()                                                                                                                                                                                                                                                                                      
           File "C:\Users\Mustafa Soylu\Documents\Projects\fzj\somesy\src\somesy\core\models.py", line 200, in get_input                                                                                                                                                                                                                              
             somesy_input = SomesyInput.from_input_file(self.input_file)                                                                                                                                                                                                                                                                              
           File "C:\Users\Mustafa Soylu\Documents\Projects\fzj\somesy\src\somesy\core\models.py", line 481, in from_input_file                                                                                                                                                                                                                        
             ret = SomesyInput(**content)                                                                                                                                                                                                                                                                                                             
           File "C:\Users\Mustafa Soylu\Documents\Projects\fzj\somesy\.venv\lib\site-packages\pydantic\main.py", line 164, in __init__                                                                                                                                                                                                                
             __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)                                                                                                                                                                                                                                          
         pydantic_core._pydantic_core.ValidationError: 1 validation error for SomesyInput                                                                                                                                                                                                                                                             
         project.repository                                                                                                                                                                                                                                                                                                                           
           URL input should be a string or URL                                                                                                                                                                                                                                                                                                        
             For further information visit https://errors.pydantic.dev/2.4/v/url_type     
```

**Comment by apirogov** [comment]
> I tried it with Windows 11 and codemeta.json creation created a permission denied error.

It looks like the newest Python docs discuss this issue we have with re-opening a tempfile on windows: https://docs.python.org/3.12/library/tempfile.html#tempfile.NamedTemporaryFile

We can try in 3.8 to follow the advice there and set `delete=False`. But then the temp file must be cleaned up manually, I believe. As you apparently have a windows machine, could you try that out?

**Comment by apirogov** [comment]
> Also, I saw this error in reading package,json input. Occurs on both Ubuntu and W11
> 
> ```shell
> DEBUG    Path package.json                                                                                                                                                                                                                                                                                                                            core.py:66
> VERBOSE  Using 'package.json' as somesy input file.                                                                                                                                                                                                                                                                                                   core.py:44
> DEBUG    Path package.json                                                                                                                                                                                                                                                                                                                            core.py:66
> ERROR    Error: 1 validation error for SomesyInput                                                                                                                                                                                                                                                                                                    util.py:24
>          project.repository                                                                                                                                                                                                                                                                                                                           
>            URL input should be a string or URL                                                                                                                                                                                                                                                                                                        
>              For further information visit https://errors.pydantic.dev/2.4/v/url_type                                                                                                                                                                                                                                                                 
> DEBUG    Traceback (most recent call last):                                                                                                                                                                                                                                                                                                           util.py:25
>            File "C:\Users\Mustafa Soylu\Documents\Projects\fzj\somesy\src\somesy\cli\util.py", line 21, in wrap_exceptions                                                                                                                                                                                                                            
>              return wrapped(*args, **kwargs)                                                                                                                                                                                                                                                                                                          
>            File "C:\Users\Mustafa Soylu\Documents\Projects\fzj\somesy\src\somesy\cli\sync.py", line 106, in sync                                                                                                                                                                                                                                      
>              somesy_input = resolved_somesy_input(                                                                                                                                                                                                                                                                                                    
>            File "C:\Users\Mustafa Soylu\Documents\Projects\fzj\somesy\src\somesy\cli\util.py", line 48, in resolved_somesy_input                                                                                                                                                                                                                      
>              somesy_input: SomesyInput = somesy_conf.get_input()                                                                                                                                                                                                                                                                                      
>            File "C:\Users\Mustafa Soylu\Documents\Projects\fzj\somesy\src\somesy\core\models.py", line 200, in get_input                                                                                                                                                                                                                              
>              somesy_input = SomesyInput.from_input_file(self.input_file)                                                                                                                                                                                                                                                                              
>            File "C:\Users\Mustafa Soylu\Documents\Projects\fzj\somesy\src\somesy\core\models.py", line 481, in from_input_file                                                                                                                                                                                                                        
>              ret = SomesyInput(**content)                                                                                                                                                                                                                                                                                                             
>            File "C:\Users\Mustafa Soylu\Documents\Projects\fzj\somesy\.venv\lib\site-packages\pydantic\main.py", line 164, in __init__                                                                                                                                                                                                                
>              __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)                                                                                                                                                                                                                                          
>          pydantic_core._pydantic_core.ValidationError: 1 validation error for SomesyInput                                                                                                                                                                                                                                                             
>          project.repository                                                                                                                                                                                                                                                                                                                           
>            URL input should be a string or URL                                                                                                                                                                                                                                                                                                        
>              For further information visit https://errors.pydantic.dev/2.4/v/url_type     
> ```

It looks to me that the model here is right in complaining and the actual bug is then in the `PackageJson` writer implementation - it needs to map from URL-string to the dict-form in `package.json`, and back

**Comment by apirogov** [comment]
LGTM

**Review by mustafasoylu — APPROVED** [review]

**Pull request merged**
