### PR TITLE
Some fixes, added metadata, added `publication_author` flag, added `somesy fill` command

### PR DESCRIPTION
**Pull request by apirogov**
I did not add tests for `somesy fill`, and just touched broken tests.

Will add tests and docs for `fill` once you're done with #34

### CODE REVIEW

**Review by mustafasoylu — CHANGES_REQUESTED** [review]
1. verbose commands in the somesy config are not effective, but it works if given in cli like `somesy -vvv fill ...`
2. Jinja gives an error if the template in not in CWD. 
```bash
$ somesy -vvv fill -i package.json -t ../../docs/_template_authors.md                           ✔  somesy   at 10:48:36  
INFO     Using provided file '/home/soylu/fzj/somesy/scratch/t1/package.json' as somesy input file.                                                              core.py:29
DEBUG    Path /home/soylu/fzj/somesy/scratch/t1/package.json                                                                                                     core.py:66
ERROR    Error: ../../docs/_template_authors.md                                                                                                                  util.py:18
DEBUG    Traceback (most recent call last):                                                                                                                      util.py:19
           File "/home/soylu/fzj/somesy/src/somesy/cli/util.py", line 15, in wrap_exceptions                                                                               
             return wrapped(*args, **kwargs)                                                                                                                               
           File "/home/soylu/fzj/somesy/src/somesy/cli/fill.py", line 62, in fill                                                                                          
             template = env.get_template(str(template_file))                                                                                                               
           File "/home/soylu/fzj/somesy/.venv/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template                                              
             return self._load_template(name, globals)                                                                                                                     
           File "/home/soylu/fzj/somesy/.venv/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template                                             
             template = self.loader.load(self, name, self.make_globals(globals))                                                                                           
           File "/home/soylu/fzj/somesy/.venv/lib/python3.10/site-packages/jinja2/loaders.py", line 126, in load                                                           
             source, filename, uptodate = self.get_source(environment, name)                                                                                               
           File "/home/soylu/fzj/somesy/.venv/lib/python3.10/site-packages/jinja2/loaders.py", line 195, in get_source                                                     
             pieces = split_template_path(template)                                                                                                                        
           File "/home/soylu/fzj/somesy/.venv/lib/python3.10/site-packages/jinja2/loaders.py", line 36, in split_template_path                                             
             raise TemplateNotFound(template)                                                                                                                              
         jinja2.exceptions.TemplateNotFound: ../../docs/_template_authors.md       
```

**Comment by apirogov** [comment]
Thanks! Both things should work fine now.

**Review by mustafasoylu — APPROVED** [review]
LGTM

**Comment by apirogov** [comment]
Thanks! Then I'll add a section in the docs and will merge it.

**Pull request merged**
